#!/bin/bash

function installAsdf() {
  if which -s asdf ; then
    return
  fi

  echo "asdf not installed, will try to install with homebrew"
  if ! brew install asdf; then
    echo "Failed to install asdf" >&2
    exit 1
  fi

  bash_line=$(brew info asdf | grep asdf/libexec/asdf.sh)
  if [ -z "$bash_line" ]; then
    echo "Didn't find the shell install script for bash/zsh to auto-install asdf in your shell" >&2
    echo "Run 'brew info asdf' to see how" >&2
    exit 1
  fi

  echo "Auto-installing asdf shell setup in:"
  echo "    - $HOME/.profile for bash"
  echo "$bash_line" >> $HOME/.profile
  eval "$bash_line"

  echo "    - $HOME/.zprofile for zsh"
  echo "$bash_line" >> $HOME/.zprofile

  echo "Restart your shell for changes to take effect"
}

function installAsdfPlugins() {
  cat .tool-versions | cut -d' ' -f1 | while IFS= read -r plugin; do
    asdf plugin add $plugin || exit 1
  done
}

## Check that homebrew is installed
if ! which -s brew ; then
  echo "Homebrew not installed, please install it and then run again" >&2
  echo "    https://brew.sh/" >&2
  exit 1
fi

## Install asdf if needed, then all asdf plugins, and all tools in asdf
echo "Install tools at the correct version"
installAsdf &&
  installAsdfPlugins &&
  asdf install

## Install all code dependencies
echo "Install code dependencies"
go mod download -x

## Install goose to manage database migrations
# I'm specifying the version so the dependencies for the cli don't get put into the go.mod file,
# which causes some incompatibilities that need to get manually sorted.
GOOSE_VERSION=$(awk '/pressly\/goose\/v3/ {print $2}' go.mod)
go install -tags='no_clickhouse no_libsql no_mssql no_mysql no_vertica no_xflag no_ydb' "github.com/pressly/goose/v3/cmd/goose@$GOOSE_VERSION"

## Install playwright dependencies
go run ./cmd/local-dev-dependencies/ playwright

## Always finish with go mod tidy
# In case we get something nasty when installing everything it'll try and sort it out,
# and because I was getting incompatible dependencies when installing the cli tools before,
# it'll be a warning if the go.mod gets broken.
go mod tidy
