#!/bin/bash
# A script to help update the go version used across all the files that need
# it set consistently, relies on asdf to manage the go version.

: ${GO_VERSION:="$1"}

if [ -z "$GO_VERSION" ]; then
  GO_VERSION="latest"
fi

## Set to the specified version, latest if none specified on the cli
asdf install golang "$GO_VERSION"
asdf local golang "$GO_VERSION"
GO_VERSION=$(grep "golang " .tool-versions | cut -d' ' -f 2)

## Update go.mod to require the specified version,
## which we then rely on in the workflow for CI
sed -I '' -E "s/^go (.*)$/go $GO_VERSION/" go.mod
