#!/bin/bash
# A script to help update the go version used across all the files that need
# it set consistently, relies on asdf to manage the go version.

: ${VERSION:=$1}

if [ -z "$VERSION" ]; then
  GOLANGCI_LINT_VERSION="latest"
fi

## Set to the specified version, latest if none specified on the cli
asdf install golangci-lint "$GOLANGCI_LINT_VERSION"
asdf local golangci-lint "$GOLANGCI_LINT_VERSION"
GOLANGCI_LINT_VERSION=$(grep golangci-lint .tool-versions | cut -d' ' -f 2)

## Update go.mod to require the specified version,
## which we then rely on in the workflow for CI
MATCHING_COMMENT="# golangci-lint version"
sed -I '' -E "s/(version:) v(.*)(  $MATCHING_COMMENT)/\1 v$GOLANGCI_LINT_VERSION\3/" .github/workflows/ci.yml
