#!/bin/bash

## Stop local-dev-dependencies if it's running
go run ./cmd/local-dev-dependencies stop

## Clean out tmp since we keep a bunch of files there
rm -rf tmp/

## Bootstrap so all dependencies are fixed
exec script/bootstrap
