name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: script/cibuild
