name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request: {}

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chromium
          - firefox


    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - run: script/cibuild
        env:
          BROWSER: ${{ matrix.browser }}
          CI: true

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.0.2  # golangci-lint version
